### ISSUE TITLE
Google analytics configuration not clear or out-of-date

### ISSUE THREAD

**Issue by yrxwin** [tea3/hexo-related-popular-posts#17]
Seems this plugin needs the following configuration setup in _config, while some fields seem a bit out-of-date (maybe just because I am not that familiar with the google API, but the dependency ga-analytics seems hasn't been updated for quite a while). Would that be possible to either update the dependency and configuration, or add some detailed guild on how to obtain the following fields? Thanks!

```
popularPosts: 
  googleAnalyticsAPI: 
    clientId:  ******. apps.googleusercontent.com            # google analytics API Service account acquired with 
    serviceEmail:  *****@developer.gserviceaccount.com      # E-mail address obtained with the google analytics API 
    key:  /hexo-project-root/path/to/google-services.pem    # With the google analytics API Path of acquired pem file 
    viewId:  12345678                                       # View ID tied with google analytics 
    dateRange:  30                                          # (Optional) Time period (days) to count PV number Default is 30 
    expiresDate:  10 
```
